INSERT into BROTHERS (DISCORD_ID, BROTHER_NAME) VALUES ('1','Matt');
INSERT into BROTHERS (DISCORD_ID, BROTHER_NAME) VALUES ('2','Ryan');
INSERT into BROTHERS (DISCORD_ID, BROTHER_NAME) VALUES ('3','Kristen');
INSERT into BROTHERS (DISCORD_ID, BROTHER_NAME) VALUES ('4','Gaines');
INSERT into BROTHERS (DISCORD_ID, BROTHER_NAME) VALUES ('5','Joe');

INSERT INTO "USER" (DISCORD_ID, GUILD_ID, SUPER_USER, MUSIC_PERMISSION, DIG_PERMISSION, MEME_PERMISSION, MUSIC_FILE_ID, SOCIAL_CREDIT) VALUES ('1', '1', true, true, true, true, '1', '250');
INSERT INTO "USER" (DISCORD_ID, GUILD_ID, SUPER_USER, MUSIC_PERMISSION, DIG_PERMISSION, MEME_PERMISSION, MUSIC_FILE_ID, SOCIAL_CREDIT) VALUES ('2', '1', true, true, true, true, '2', '250');
INSERT INTO "USER" (DISCORD_ID, GUILD_ID, SUPER_USER, MUSIC_PERMISSION, DIG_PERMISSION, MEME_PERMISSION, MUSIC_FILE_ID, SOCIAL_CREDIT) VALUES ('3', '1', true, true, true, true, '3', '250');
INSERT INTO "USER" (DISCORD_ID, GUILD_ID, SUPER_USER, MUSIC_PERMISSION, DIG_PERMISSION, MEME_PERMISSION, MUSIC_FILE_ID, SOCIAL_CREDIT) VALUES ('4', '1', true, true, true, true, '4', '250');
INSERT INTO "USER" (DISCORD_ID, GUILD_ID, SUPER_USER, MUSIC_PERMISSION, DIG_PERMISSION, MEME_PERMISSION, MUSIC_FILE_ID, SOCIAL_CREDIT) VALUES ('5', '1', true, true, true, true, '5', '250');

INSERT INTO MUSIC_FILES(FILE_NAME, MUSIC_BLOB, ID, FILE_VOL) VALUES (null, null, 1, 0);
INSERT INTO MUSIC_FILES(FILE_NAME, MUSIC_BLOB, ID, FILE_VOL) VALUES (null, null, 2, 0);
INSERT INTO MUSIC_FILES(FILE_NAME, MUSIC_BLOB, ID, FILE_VOL) VALUES (null, null, 3, 0);
INSERT INTO MUSIC_FILES(FILE_NAME, MUSIC_BLOB, ID, FILE_VOL) VALUES (null, null, 4, 0);
INSERT INTO MUSIC_FILES(FILE_NAME, MUSIC_BLOB, ID, FILE_VOL) VALUES (null, null, 5, 0);