name: Publish wiki

on:
  push:
    branches: [master]
    paths:
      - wiki/**
      - .github/workflows/publish-wiki.yml
  workflow_dispatch:

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  generate-and-publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build and run Spring Boot app
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Fetch from GitHub Secrets
          TOKEN: ${{ secrets.TOKEN }}  # Fetch from GitHub Secrets
        run: |
          ./gradlew bootJar  # Or ./mvnw clean package if you're using Maven
          java -jar build/libs/toby-bot-6.0-SNAPSHOT.jar &  # Start the app in the background
          sleep 20  # Give the app some time to start

      - name: Fetch Commands Documentation
        run: |
          # Fetch the commands documentation from the locally running instance
          curl -X GET "http://localhost:8080/commands/wiki" -o "wiki/Commands.md"
          echo "Commands.md generated in the wiki folder."

      - name: Commit changes to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add the new/updated Commands.md
          git add wiki/Commands.md

          # Commit changes if there are any
          git diff-index --quiet HEAD || git commit -m "Update Commands.md in wiki"

      - name: Publish to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
