name: Update Wiki

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki  # Checkout the wiki repository
          path: wiki  # Save it in the 'wiki' directory

      - name: Get Command Documentation
        env:
          BASE_URL: ${{ vars.BASE_URL }}
        run: |
          # Fetch commands and save to a temporary file in the wiki directory
          TEMP_FILE="wiki/Commands_temp.md"
          if curl -X GET "$BASE_URL/commands/wiki" -o "$TEMP_FILE"; then
            echo "Successfully fetched command documentation."
          else
            echo "Failed to fetch command documentation."
            exit 1  # Exit with an error code if curl fails
          fi

      - name: Check for Differences
        run: |
          # Log the contents of the temporary Commands file
          echo "=== Contents of Commands_temp.md ==="
          cat "wiki/Commands_temp.md"
          echo "====================================="

          # Log the contents of the existing Commands file
          echo "=== Contents of Commands.md ==="
          cat "wiki/Commands.md"
          echo "====================================="

          # Compare the fetched file with the existing Commands.md
          if ! diff -q "wiki/Commands_temp.md" "wiki/Commands.md" > /dev/null; then
            echo "Differences found. Updating Commands.md."
            # If differences are found, overwrite the existing Commands.md
            mv "wiki/Commands_temp.md" "wiki/Commands.md"
          else
            echo "No differences found. Skipping update."
            exit 0  # Exit successfully without making changes
          fi

      - name: Commit and Push Changes
        run: |
          cd wiki  # Navigate to the wiki directory
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Stage any changes
          git add .
          
          # Commit and push changes if there are any
          git diff-index --quiet HEAD || git commit -m "Update commands documentation" && git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
